app = "hex-ade-backend"
primary_region = "iad"

[build]
  dockerfile = "server/Dockerfile"

[env]
  LOG_LEVEL = "info"
  PYTHONUNBUFFERED = "1"
  PORT = "8888"

[[services]]
  internal_port = 8888
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    http_options = { compress = true }

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512